# Numpy 

In [2]:
import numpy as np   #her np is alias of numpy
# numpy makes list into array. 

In [3]:
l=[3,4,5,6,7,'Alankar']

In [4]:
type(l)

list

In [6]:
np.array(l)           #converting list into array

array(['3', '4', '5', '6', '7', 'Alankar'], dtype='<U11')

In [8]:
type(np.array(l))    # 1D array

numpy.ndarray

In [13]:
np.array([[1,2,3]])    # 2D array

array([[1, 2, 3]])

In [14]:
np.array([[[1,2,5]]])    # 3-D array

array([[[1, 2, 5]]])

In [15]:
np.array([[[[3,5,7]]]])   #4-D array

array([[[[3, 5, 7]]]])

## mat

In [17]:
np.mat([1,2,3]) # Convering data into metrix

matrix([[1, 2, 3]])

In [23]:
arr = np.array([3,4,5,6,7])
print(arr)
print(arr[0])                     #works in simar way as string 
print(arr[0:3])
print(arr[0:3:2])

[3 4 5 6 7]
3
[3 4 5]
[3 5]


In [35]:
arr1 = np.array([ [1,2] , [3,4] ])
print(arr1)
print('\n')
print(arr1[1][1])
#or
print(arr1[1,1]) 

[[1 2]
 [3 4]]


4
4


In [36]:
arr2 = np.array([ [1,2] , [3,4] , [4,5]])
print(arr2[2][1])
#or
print(arr2[2,1])

5
5


## asarray 

In [39]:
np.asarray([3,4,5,6])          # asarray & ndarray gives same result

array([3, 4, 5, 6])

In [41]:
np.asarray([3,4,5,6], dtype = np.float32)

array([3., 4., 5., 6.], dtype=float32)

In [42]:
np.asarray([3,4,5,6], dtype = np.float64)

array([3., 4., 5., 6.])

## AsAnyArray

In [44]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [45]:
np.asanyarray(np.mat([1,2,3,4]))

matrix([[1, 2, 3, 4]])

In [48]:
np.fromfunction(lambda i,j : i*j, (3,3), dtype = int)                   # fromfunction helps in creating array
                                                                    #(3,3) -> shape
    # i is for rows & j is for column

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [49]:
np.fromfunction(lambda i,j : i+j, (3,3), dtype = int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [53]:
np.fromfunction(lambda i,j,k : i+j+k, (3,3,2), dtype = int)                # Beyond 3d is not possible

array([[[0, 1],
        [1, 2],
        [2, 3]],

       [[1, 2],
        [2, 3],
        [3, 4]],

       [[2, 3],
        [3, 4],
        [4, 5]]])

## fromiter 

In [ ]:
np.fromiter()

In [4]:
#example1:-
for i in 5:
    print(i)

TypeError: 'int' object is not iterable

In [5]:
#example2:-
for i in 'Alan':
    print(i,end='')

Alan

In [6]:
#example3:-
for i in 's':
    pass

In [7]:
#example4:-
for i in [1,2,3,4]:
    pass

In [8]:
#example5:-
s="Alan"
next(s)

TypeError: 'str' object is not an iterator

In [9]:
#example6:-
l=[1,2,3,4]
next(l)

TypeError: 'list' object is not an iterator

In [13]:
#example7:-
r = range(4)
next(r)

TypeError: 'range' object is not an iterator

In [11]:
#example8:-
a = 'Alan'
i = iter(s)
print(next(i))
print(next(i))
print(next(i))
print(next(i))

A
l
a
n


In [12]:
print(next(i))  # error since nothing after this

StopIteration: 

In [69]:
#   SEE dif. iterator and iterable


 #see difference between Example 1 and 5,6,7

# video

In [3]:
l=[1,2,3,4]
next(l)

TypeError: 'list' object is not an iterator

In [71]:
l=[1,2,3,4]
i = iter(l)
next(i)            #now it will work, this is same thimg that happens in for loop while accesing string

1

In [73]:
np.fromiter([1,2,3,4,5], dtype = float)

array([1., 2., 3., 4., 5.])

In [77]:
np.fromstring('Alan kar', sep = " ")

<ipython-input-77-5cfebc7ad0de>:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('Alan kar', sep = " ")


array([], dtype=float64)

In [78]:
np.fromstring('251 136246 24', sep = " ")

array([2.51000e+02, 1.36246e+05, 2.40000e+01])

## ndim 

In [81]:
l= [3,4,5,6,7,8,8]
arr = np.array(l)
arr


array([3, 4, 5, 6, 7, 8, 8])

In [82]:
arr.ndim                            

1

## shape

In [83]:
arr.shape

(7,)

## shape

In [84]:
arr.dtype

dtype('int32')

## arange

In [85]:
list(range(0,8))

[0, 1, 2, 3, 4, 5, 6, 7]

In [86]:
list(range(0,7.6))

TypeError: 'float' object cannot be interpreted as an integer

In [89]:
np.arange(0,4.6,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6,
       3.9, 4.2, 4.5])

## linespace

In [94]:
np.linspace(1,5)              #bydefaultscale is 50

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [95]:
np.linspace(1,5,10)              #generate 10 numbers

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

## zeros

In [98]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [99]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [101]:
np.zeros((2,4,3,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [102]:
# ones

In [103]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [105]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [112]:
np.ones((4,5)) +1           #sima;lary *,/,...

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

## empty

In [110]:
np.empty((3,5))

array([[0.3, 0.6, 0.9, 1.2, 1.5],
       [1.8, 2.1, 2.4, 2.7, 3. ],
       [3.3, 3.6, 3.9, 4.2, 4.5]])

## eye
#### generates identity metrix

In [111]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## random.rand 

In [115]:
np.random.rand(3,5)

array([[0.22040498, 0.09607106, 0.36337161, 0.89602195, 0.12710527],
       [0.3266333 , 0.51453419, 0.49967411, 0.3562441 , 0.63649737],
       [0.25091111, 0.42164106, 0.76947527, 0.52820853, 0.87632465]])

## random.randn 

In [117]:
np.random.randn(4,5)           #creates normally distributed

array([[-0.56942277, -0.87267853, -0.35614133,  1.46132185, -2.09817433],
       [ 1.40414199,  0.11009964,  1.9725405 , -2.27292686,  0.22185696],
       [-1.01999006, -0.38983442, -0.16825148, -1.0622818 ,  0.42926899],
       [ 0.08750335, -1.08804329,  0.69563729, -0.8000532 ,  0.66619026]])

##  random.randint

In [120]:
np.random.randint(3,40)        #generates random number

27

In [125]:
np.random.randint(3,40,size = 60)   #or np.random.randint(3,40,60)

array([34, 22, 35, 30, 17, 20,  6, 24, 37, 36, 22, 31, 18, 36,  5,  7, 28,
       17, 37, 33, 25, 31,  6, 21, 10, 30, 17,  7, 31,  5, 37, 14, 18, 29,
       27, 19, 32, 34, 39, 12,  9, 21, 26,  4, 12, 32, 18, 37, 37, 34, 36,
        5,  5, 30, 32, 35, 25, 17, 15, 32])

In [126]:
np.random.randint(2,7,(4,5))

array([[3, 3, 2, 4, 3],
       [6, 5, 4, 2, 3],
       [2, 6, 4, 5, 6],
       [4, 2, 4, 2, 5]])

## reshape 

In [129]:
arr = np.random.randint(2,7,(4,5))
print(arr.shape)
print(arr)

(4, 5)
[[2 3 2 6 4]
 [3 4 5 4 5]
 [4 5 3 5 6]
 [4 3 3 6 2]]


In [130]:
arr.reshape(1,4,5)

array([[[2, 3, 2, 6, 4],
        [3, 4, 5, 4, 5],
        [4, 5, 3, 5, 6],
        [4, 3, 3, 6, 2]]])

In [131]:
arr.reshape(10,2)

array([[2, 3],
       [2, 6],
       [4, 3],
       [4, 5],
       [4, 5],
       [4, 5],
       [3, 5],
       [6, 4],
       [3, 3],
       [6, 2]])

In [133]:
print(arr.max())
print(arr.min())

6
2


In [138]:
arr[0][1] = 222
arr

array([[  2, 222,   2,   6,   4],
       [  3,   4,   5,   4,   5],
       [  4,   5,   3,   5,   6],
       [  4,   3,   3,   6,   2]])

#### matrix multiplication  

In [150]:
mat1 = np.random.rand(3,3,)
mat2 = np.random.rand(3,3,)
print(mat1)
print('\n')
print(mat2)

[[0.44831843 0.45979672 0.8205024 ]
 [0.10479796 0.94362367 0.77969782]
 [0.19510767 0.28529722 0.75002965]]


[[0.9207451  0.32790602 0.54208379]
 [0.62378654 0.539153   0.90192636]
 [0.07991114 0.54646628 0.527929  ]]


In [151]:
mat1 * mat2       #this is not matric multiplication , element multiplication

array([[0.412787  , 0.15077011, 0.44478105],
       [0.06537156, 0.50875753, 0.70323002],
       [0.01559128, 0.15590531, 0.39596241]])

In [152]:
mat1 = np.random.randint(1,4,(3,3))
mat2 = np.random.randint(1,4,(3,3))
print(mat1)
print('\n')
print(mat2)
print('\n')
print('matrix miltiplucation=>')
print(mat1@mat2)

[[2 1 1]
 [2 3 1]
 [1 1 2]]


[[3 2 1]
 [2 2 2]
 [2 3 1]]


matrix miltiplucation=>
[[10  9  5]
 [14 13  9]
 [ 9 10  5]]


In [154]:
1/0

ZeroDivisionError: division by zero

In [155]:
arr/0

<ipython-input-155-39e2cbdaf753>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [157]:
# Transpose of matrix
mat1.T

array([[2, 2, 1],
       [1, 3, 1],
       [1, 1, 2]])

In [158]:
arr


array([[  2, 222,   2,   6,   4],
       [  3,   4,   5,   4,   5],
       [  4,   5,   3,   5,   6],
       [  4,   3,   3,   6,   2]])

In [159]:
arr**2

array([[    4, 49284,     4,    36,    16],
       [    9,    16,    25,    16,    25],
       [   16,    25,     9,    25,    36],
       [   16,     9,     9,    36,     4]], dtype=int32)

In [161]:
np.exp(arr)

array([[7.38905610e+00, 2.59044862e+96, 7.38905610e+00, 4.03428793e+02,
        5.45981500e+01],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02, 5.45981500e+01,
        1.48413159e+02],
       [5.45981500e+01, 1.48413159e+02, 2.00855369e+01, 1.48413159e+02,
        4.03428793e+02],
       [5.45981500e+01, 2.00855369e+01, 2.00855369e+01, 4.03428793e+02,
        7.38905610e+00]])

In [162]:
np.log10(arr)

array([[0.30103   , 2.34635297, 0.30103   , 0.77815125, 0.60205999],
       [0.47712125, 0.60205999, 0.69897   , 0.60205999, 0.69897   ],
       [0.60205999, 0.69897   , 0.47712125, 0.69897   , 0.77815125],
       [0.60205999, 0.47712125, 0.47712125, 0.77815125, 0.30103   ]])

In [163]:
np.sqrt(arr)

array([[ 1.41421356, 14.89966443,  1.41421356,  2.44948974,  2.        ],
       [ 1.73205081,  2.        ,  2.23606798,  2.        ,  2.23606798],
       [ 2.        ,  2.23606798,  1.73205081,  2.23606798,  2.44948974],
       [ 2.        ,  1.73205081,  1.73205081,  2.44948974,  1.41421356]])

In [164]:
np.pi

3.141592653589793